name: flutter_sync_tree
description: A high-performance, hierarchical synchronization framework with weighted progress and throttling for Flutter.
version: 1.0.2
homepage: https://github.com/friend-22/flutter-sync-tree
repository: https://github.com/friend-22/flutter-sync-tree
issue_tracker: https://github.com/friend-22/flutter-sync-tree/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0